const actions = {
  SET_LOADING: 'SET_LOADING',
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
  SET_SELECTED_SYMBOL: 'SET_SELECTED_SYMBOL',
  SET_SYMBOLS: 'SET_SYMBOLS',
  APPEND_PRICES: 'APPEND_PRICES',
  SET_DEPTH: 'SET_DEPTH',
};

export default actions;
