const actions = {
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
  SET_USER_THEME: 'SET_USER_THEME',
  SET_LOADING: 'SETLOADING',
  SET_WORKSPACE: 'SET_WORKSPACE',
  SET_MENU_EXPANDED: 'SET_MENU_EXPANDED',
  APPEND_NOTIFICATION: 'APPEND_NOTIFICATION',
  APPEND_ALERT: 'APPEND_ALERT',
  RESET_NOTIFICATIONS: 'RESET_NOTIFICATIONS',
  RESET_ALERTS: 'RESET_ALERTS',
};

export default actions;
